In [1]:
import pandas as pd

In [3]:
countries_data_name = './data/countries.csv'
countries_data = pd.read_csv(countries_data_name)

In [4]:
countries_data.head()

,iso_alpha2,iso_alpha3,iso_numeric,name,official_name,ccse_name,density,fertility_rate,land_area,median_age,migrants,population,urban_pop_rate,world_share
0,AF,AFG,4,Afghanistan,Islamic Republic of Afghanistan,Afghanistan,60,4.6,652860,18.0,-62920.0,38928346,0.25,0.0050
1,AL,ALB,8,Albania,Republic of Albania,Albania,105,1.6,27400,36.0,-14000.0,2877797,0.63,0.0004
2,DZ,DZA,12,Algeria,People's Democratic Republic of Algeria,Algeria,18,3.1,2381740,29.0,-10000.0,43851044,0.73,0.0056
3,AD,AND,20,Andorra,Principality of Andorra,Andorra,164,NaN,470,NaN,NaN,77265,0.88,0.0000
4,AO,AGO,24,Angola,Republic of Angola,Angola,26,5.6,1246700,17.0,6413.0,32866272,0.67,0.0042